### ISSUE TITLE
enchancement: Dynamic mode for WS2812B

### ISSUE THREAD

**Issue by Partizan7676** [HomeKidd/Homekit-WS2812B-controller#1]
In Maxim Kulkin repo https://github.com/maximkulkin/esp-homekit-demo/tree/master/examples/led_strip_animation an example of that. You get two devices after pairing one for color, second for amazing animated effects.

**Comment by HomeKidd** [comment]
I’ve used this one too with some modifications, but at the moment this code doesnt support it. I think this will be an another repo for those who want the Neopixel FX! But it will be supported so stay tuned!🙃

**Comment by HomeKidd** [comment]
@Partizan7676 I've added the animated FX into my [To-Do list](https://github.com/HomeKidd/Homekit-WS2812B-controller/wiki/To-Do) ! 😉
