### ISSUE TITLE
Effects as a switch

### ISSUE THREAD

**Issue by csupi003** [HomeKidd/Homekit-WS2812B-controller#14]
Hello, 
Would it be possible to have effects as a switch in the Home app? 
Obviously not all, but a few favourites. 

Right now I'm using homebridge-wled and hb-http-switch to achive similar to it. 

Thanks,

**Comment by HomeKidd** [comment]
Hi!
 Sadly no, Home app doesnt support any 3rd party/custom characteristics, and for the effects (even for a few one)  it creates a lot mess in the Home app. Also adjusting the speed of the effects and the power on behaviour requires the Eve app.
All you can do is setup an automation/scene within the Eve app and this will show up in the Home app also 🤓
