### ISSUE TITLE
PCB Designs

### ISSUE THREAD

**Issue by JaniniRami07** [HomeKidd/Homekit-WS2812B-controller#20]
Hey, This is more than of a question than an issue, I want to ask what software did you use to design your PCB, I have downloaded the design for pcb v.2 but I have no idea what program to install to use it.

**Comment by HomeKidd** [comment]
Hi! Theres a dedicated [Wiki page](https://github.com/HomeKidd/Homekit-WS2812B-controller/wiki/Build-Instructions) for the installing process! 🤓
