### ISSUE TITLE
Electrodragon Board

### ISSUE THREAD

**Issue by caiotadashi** [HomeKidd/Homekit-WS2812B-controller#21]
Hey guys! Does the Homekit WS2812B controller works on this Electrodragon's board? (https://www.electrodragon.com/product/esp-led-strip-board/)

**Comment by HomeKidd** [comment]
Hi! 
If the mentioned PCB using `GPIO0` for button and `GPIO3` as WS2812B data pin it can be used. More information can be found at the [Wiki page](https://github.com/HomeKidd/Homekit-WS2812B-controller/wiki#basic-information) 🤓
