### ISSUE TITLE
static effects

### ISSUE THREAD

**Issue by MajorTom1301** [HomeKidd/Homekit-WS2812B-controller#23]
Hey, 
I would like to set static effects.
For example, a color gradient from one color to the other across all LEDs. (white to red, in all brightness levels)
or rainbow colors that don't move ...
is that possible somehow?

best regards
MajorTom1301

**Comment by HomeKidd** [comment]
Hi!
That feature wont work yet, effects are just an extra feature, the main feature of this is an RGB HomeKit LED strip🤓
Maybe in a future release i’ll add option, added it for my ToDo list.✌️
Until that i close the issue 😉
