### ISSUE TITLE
Homekit WS2812B effects

### ISSUE THREAD

**Issue by tibur79** [HomeKidd/Homekit-WS2812B-controller#25]
hello I have installed the Homekit WS2812B I have the latest version of ios and last of eve the device works well the only thing wrong I do not find the effects on the app eve made with wemos d1 mini

**Comment by HomeKidd** [comment]
Hi! Which fimware version are you running on? Just because i can see the Effects tab in the Eve app and the last 5-6 release should have that 😄

**Comment by HomeKidd** [comment]
@tibur79  Any update?

**Comment by tibur79** [comment]
Thanks I did everything and it's so cool !!!

**Comment by HomeKidd** [comment]
> Thanks I did everything and it's so cool !!!
> […](#)

You its working? Because I'll close the issue in that case..

**Comment by tibur79** [comment]
Yesssss
