### ISSUE TITLE
Question: Add Reboot function

### ISSUE THREAD

**Issue by Caleb79** [HomeKidd/Homekit-WS2812B-controller#28]
Hi,
although you already released a new version to Git but I have a question:
Is it possible to add a reboot functionality to the button, like:
pressing 3 seconds and then reboot

Would that be possible?
The reason is just for, let's say investigation purpose and sometimes the issue with no response.

Thanks.

**Comment by HomeKidd** [comment]
Some of my newer FWs have this function, but i've forget to add it here 😅
Now its done with the latest [2.2.2 release](https://github.com/HomeKidd/Homekit-WS2812B-controller/releases/tag/2.2.2) 😄

Long pressing is preserved for Resetting, but Triple pressing the button will reboot the ESP within 5 seconds, but only when Child Lock function is not active!
