### ISSUE TITLE
RGBW support

### ISSUE THREAD

**Issue by dbartelmus** [HomeKidd/Homekit-WS2812B-controller#3]
Any possibility for RGBW with sk6812??

**Comment by HomeKidd** [comment]
Currently i'm not planning to add this feature. Normal SK6812 RGB is supported, but RGBW version is not.

**Comment by HomeKidd** [comment]
I’ve made changes to the code, only WS281X variants are supported! But these LED strips are supporting Color Temperature Characteristic within HomeKit!🙌
