### ISSUE TITLE
No Library .zip in the Download folder.

### ISSUE THREAD

**Issue by MKProdukt** [HomeKidd/Homekit-WS2812B-controller#30]
Hi, if i try add you Prog. to the Arduino IDE i receive an error message that there is no valid library.
Could you please update this, cause i really want to try out your awesome scretch.

Thanks in advance. - Max

**Comment by HomeKidd** [comment]
Hi!
You cannot find any Library because this is not a Library, all my projects are comes in premade .bin files and FYI its not based on Arduino!
Please read the Wiki how to install it!
