### ISSUE TITLE
Number of LEDs

### ISSUE THREAD

**Issue by JefersonSchramm** [HomeKidd/Homekit-WS2812B-controller#31]
Hello.

Is it possible to increase the number os LEDs? The limit is 500 and I need 600 ( I have 2 LED strips with 300 LEDs each).

Thanks

**Comment by HomeKidd** [comment]
Hi!

No, the [number of LEDs are limited to 500](https://github.com/HomeKidd/Homekit-WS2812B-controller/wiki#basic-information) because increasing the it more than 500 causes problems (takes too much memory)
