### ISSUE TITLE
mdns_recv: pbuf too small

### ISSUE THREAD

**Issue by dj-nic** [HomeKidd/Homekit-WS2812B-controller#34]
Hey
I just tried to setup the code and add it to HomeKit.
In homekit it says the device couldn't be found... so i looked up in the serial monitor and it keeps saying mdns_recv: pbuf too small
even the wifi is connected and the service is running.
Can someone please help me with that?
thanks in advance!

![image](https://user-images.githubusercontent.com/70818245/103445933-021b5980-4c7a-11eb-8b9e-652edfac6022.png)

**Comment by HomeKidd** [comment]
Hi!

Which ESP did you use and which settings for flash it? Also which firmware version are you running on?

[Others have this issue](https://github.com/maximkulkin/esp-homekit-demo/issues/11) when the flash size params was incorrect! 

Please erase the flash and try again with the correct settings for flash size:

> ESP-01 has 512kb -> 4mbit flash size NOT supported
> ESP-01S has 1MB -> 8mbit flash size
> ESP-07/12E/12F/12S has 4MB -> 32mbit flash size


Actually i've never seen this issue 😅 all my ESPs are running without any errors with the latest version of this code.

**Comment by dj-nic** [comment]
Hey!

Im using an ESP8266 D1 Mini for this and i will try it out with other flash sizes soon
because im a bit busy in the last time.
Thanks for the response!

**Comment by HomeKidd** [comment]
Any update?

**Comment by dj-nic** [comment]
OH Sorry I forgot to answer here 😅.   Yes I tried it again to reflash with other options and so on... It crash/restarts at some options and on the others I still get the error with pbuf to small.

**Comment by HomeKidd** [comment]
Did you tried it with other Wemos?

**Comment by dj-nic** [comment]
No actualy not because it was the last that wasn't in use. But it is Working if you think it is might broken. Right now it's plugged in into my pc with an GRB stripe for Ambilight. I Will buy some new esp8266 and esp 32 (hopefully) on monday.

**Comment by dj-nic** [comment]
Well I got it working now with a new chip idunno why the other chip said "no" and I'm sorry too for other useres that maybe have the same problem and don't know how to fix them... + some effects are a bit laggy is it maybe because I flashed the chip to 40MHz instead of 80MHz?
**Edit:** Nevermind I flashed with 80MHz -> didn't fixed it. Set the transiton in the eve app from default to fast -> **Fixed it.**
![image](https://user-images.githubusercontent.com/70818245/107892831-f208c200-6f27-11eb-8e76-68439243fd2d.jpeg)
