### ISSUE TITLE
Change effects speed label:"Feature Request" 

### ISSUE THREAD

**Issue by Willem-Si** [HomeKidd/Homekit-WS2812B-controller#36]
is it possible to change the speed of the effects? that for example effect 9 (Rainbow Cycle) cycles faster.

**Comment by HomeKidd** [comment]
Hi!
The [speed of effects can be changed via the Eve app](https://github.com/HomeKidd/Homekit-WS2812B-controller/wiki/HomeKit-Setup#transitions-and-power-behaviour) in 4 steps using Transitions settings ✌️

**Comment by Willem-Si** [comment]
Hi!

Thanks for the quick response! Okay! I had completely overlooked that option! 👍
