### ISSUE TITLE
Question: Light Effect Characteristic?

### ISSUE THREAD

**Issue by dsully** [HomeKidd/Homekit-WS2812B-controller#40]
Hi - I'm trying to find more info on the (Eve?) Light Effect Characteristic  you implemented as UUID:

F8600004-079E-48FF-8F27-9C2605A29F52

Do you have any pointers for more information?

Thanks

**Comment by HomeKidd** [comment]
Hi!

Its not implemented by Eve, i've created this characteristic.

```
    permissions : homekit_permissions_paired_read, homekit_permissions_paired_write, homekit_permissions_notify
    min_value : 0
    max_value : 53
    min_step : 1
    format : HOMEKIT_UINT8
```

You can define any custom characteristics (and services) you want with a custom UUID but these characteristics are not showing up in the Home app, only in 3rd party apps 🤓
