### ISSUE TITLE
Source code missing?

### ISSUE THREAD

**Issue by LAPISK** [HomeKidd/Homekit-WS2812B-controller#43]
Hi,
I'm not sure this is the right place to ask, but I'm looking for the source code into the directory src but I find only two .bin files.
I suppose, that these files are just for flashing the ESP.
This happens also if I download the Source code.zip.
I expected to find some C or similar source code, I'm missing something?
Thanks.

**Comment by HomeKidd** [comment]
Hi!
Take a look at issue #33 and #37 😉
