### ISSUE TITLE
HomeKid_NeoPixel_v3 Gerber files not found

### ISSUE THREAD

**Issue by novacom34** [HomeKidd/Homekit-WS2812B-controller#44]
Hi. Thanks for you pcb. Could you please share Gerber files for v3 pcb. Because there is only for version 2.0.2 in release. Thanks.

**Comment by HomeKidd** [comment]
Hi!

The v3 pcb was sponsored by PCBWay so due to licenses i can't make it public. It can be ordered **only** from [PCBway](https://www.pcbway.com/project/shareproject/Apple_HomeKit_ESP8266_WS2812FX_Driver.html)
