### ISSUE TITLE
Does this project work on ESP32 as well ?

### ISSUE THREAD

**Issue by alialki** [HomeKidd/Homekit-WS2812B-controller#45]
I was thinking to start with this project but i have couple of extra ESP32 boards, so i was wondering if this can be done on an esp32 or only works on esp8266

**Comment by HomeKidd** [comment]
Hi!

All my projects are built around ESP8266 only so both the code and [PCBs](https://github.com/HomeKidd/Homekit-WS2812B-controller/wiki/PCB-Design) are made for ESP8266. I'm not planning to make it for ESP32 because of cost issues and because the ESP8266 still enough to run the firmware.
