### ISSUE TITLE
Incompatible with HomeKit?

### ISSUE THREAD

**Issue by Bakak** [HomeKidd/Homekit-WS2812B-controller#55]
i flashed successfully, then configured WiFi. All went well. When i try to add it to HomeKit, or the EVE app, I first get the warning, that the devce is not certified, then it says the device is incompatible with HomeKit

**Comment by Elecmcqueen** [comment]
first Time !
thank you for this very cool Project.

I have the same Problem.
Erase and Flashing of the Device was all successful.
But HomeKit says that the Device is not compatible with HomeKit.

**Comment by andywaplinger** [comment]
@Bakak @Elecmcqueen are you able to post screenshots of the message? I also get a warning, but I have the option of "Add Anyways" and can successfully add my controller.

**Comment by fmland2** [comment]
I had issues setting up with HomeKit as well. It told me it was an invalid code. I made sure i was using the latest build on the ledstrip.bin as well.

*Edit: I retried, and it accepted it the following time. All attempts were with the QR code.
