### ISSUE TITLE
Still supported?

### ISSUE THREAD

**Issue by greengiant912** [HomeKidd/Homekit-WS2812B-controller#59]
Hello,

I recently built the boards that you designed, but it seems like some of the files are missing. Such as ledstrip.bin or main.bin according to the build instructions these are required to write to the module. 

It looks like it was deleted at some point. 

Thanks!

**Comment by HomeKidd** [comment]
Hi!
Ledstrip.bin is under the [releases tab](https://github.com/HomeKidd/Homekit-WS2812B-controller/releases/tag/2.2.3). The other files are common ones, check out my other [repositories](https://github.com/HomeKidd/ESP8266-HomeKit-Stateless-Button-Elgato-Eve-Button/wiki/Build-Instructions), it should be there 👌
