### ISSUE TITLE
Can you please make it work with mosfets and standard 4 pin led strips?

### ISSUE THREAD

**Issue by ltlklr** [HomeKidd/Homekit-WS2812B-controller#8]

**Comment by HomeKidd** [comment]
Yes, i'm planning to do that. [MagicHome](http://s.click.aliexpress.com/e/bF57DAEM) controllers are great hardwares for this, but currently i not have any of these...but i'm ordered one for testing 😄

**Comment by ltlklr** [comment]
Wow, that was a fast reply. Im looking forward to the update.

**Comment by HomeKidd** [comment]
For standard RGB/RGBW [MagicHome](https://github.com/HomeKidd/HomeKit-MagicHome-LED-controller-Elgato-Eve-Light-Strip) controllers the firmware is now available! 😄
